import "./globals.css";
import {
  SidebarProvider,
  NextUiProviders,
  WishListProvider,
} from "./contexts/index.js";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";


export const metadata = {
  title: "Maharaja",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextUiProviders>
          <SidebarProvider>
            <WishListProvider>
              <div className="bg-[#E3E3E3] px-4 md:px-6">
                <Navbar />
                {children}
                <Footer />
              </div>
            </WishListProvider>
          </SidebarProvider>
        </NextUiProviders>
      </body>
    </html>
  );
}
